const deals = [
  {
    _id: "1",
    category: "beauté",
    description: "Mini soins de mains + Pose vernis permanent",
    pictureURL: "/images/Soins-des-mains.jpg",
    date: "20/06/2021",
    price: 10,
    promo:"dt au lieu de 35dt",
    location: "Manar",
    details: "Mini soins de mains  & Pose vernis permanent",
  },
  {
    _id: "2",
    category: "beauté",
    description: "Soin capillaire + Brushing",
    pictureURL: "/images/soin-capillaire.jpg",
    date: "20/06/2021",
    price: 30,
    promo:"dt au lieu de 70dt",
    location: "Menzah6",
    details: "Soin capillaire & Brushing",
  },
  {
    _id: "3",
    category: "beauté",
    description: "Cils à cils + maquillage de jour + épilation sourcils",
    pictureURL: "/images/maquillage.png",
    date: "20/06/2021",
    price: 50,
    promo:"dt au lieu de 100dt",
    location: "Menzah8",
    details: "Cils à cils & maquillage de jour & épilation sourcils",
  },

  {
    _id: "4",
    category: "détente",
    description: "massage au bambou et modelage du visage",
    pictureURL: "/images/massage-bamboo.webp",
    date: "20/06/2021",
    price: 40,
    promo: "dt au lieu de 90 dt",
    location: "Manar",
    details: "massage au bambou & modelage du visage",
  },
  {
    _id: "5",
    category: "détente",
    description: "Un massage relaxant corps complet (40 min)",
    pictureURL: "/images/massage-corps.jpg",
    date: "20/06/2021",
    price: 35,
    promo:"dt au lieu de 70dt",
    location: "Tunis",
    details: "Un massage relaxant corps complet (40 min)",
  },
  {
    _id: "6",
    category: "détente",
    description: "Massage californien aux pierres chaudes",
    pictureURL: "/images/massage-pierres.jpg",
    date: "20/06/2021",
    price: 40,
    promo:"dt au lieu de 80dt",
    location: "Ennasr",
    details: "Massage californien aux pierres chaudes",
  },
  {
    _id: "7",
    category: "sport",
    description: "Abonnement mensuel en accés illimité à la salle de sport",
    pictureURL: "/images/abonnement-mensuel.webp",
    date: "20/06/2021",
    price: 40,
    promo:"dt au lieu de70 dt",
    location: "Marsa",
    details: "Abonnement mensuel en accés illimité à la salle de sport",
  },
  {
    _id: "8",
    category: "sport",
    description: "abonnement de 3 mois(H/F) en illimité à la salle de sport",
    pictureURL: "/images/abonnement-3-mois.jpg",
    date: "20/062021",
    price: 99,
    promo: "dt au lieu de 180dt",
    location: "Aouina",
    details: "abonnement de 3 mois(H/F) en illimité à la salle de sport",
  },
];
export default deals;
